name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    concurrency: dev
    steps:
      - name: deploy
        # ...deployment-specific steps
